package rules

//import com.sample.DroolsTest.*;
import com.sample.*;

/*
good lyrics
medium lyrics
lyrics dont matter
quit
*/

rule "Ad"
    salience -1
	when
	then
        Comm.showMessage("Nasz baza nie zawiera zespołu dla Ciebie, ale wybierz Hindsight! Alex się ucieczy <spójrz no na niego>");
end

rule "guitar"
    when
        Fact(name("guitar"), value(true))
    then
        Comm.showMessage("artist dla Ciebie to guitar");
end

rule "Opeth"
    when
        Fact(name("metal"), value(true))
        (or
            Fact(name("gutiar"), value(true))
            Fact(name("drums"), value(true))
            Fact(name("bass"), value(true))
        )
        Fact(name("instrumental"), value(false))
        Fact(name("scream"), value(true))
        Fact(name("male vocal"), value(true))
        Fact(name("opera"), value(false))
        Fact(name("solo"), value(false))
        (or
            Fact(name("alt metal"), value(true))
            Fact(name("progressive metal"), value(true))
            Fact(name("folk metal"), value(true))
            Fact(name("death metal"), value(true))
        )
        Fact(name("long songs"), value(true))
        not Fact(name("dzielnia"), value(true))
        (or
            Fact(name("high tempo"), value(true))
            Fact(name("mid tempo"), value(true))
        )
    then
        Comm.showMessage("Zespół dla Ciebie to Opeth");
end

rule "Glenn Miller"
    when
        Fact(name("jazz"), value(true))
        Fact(name("opera"), value(false))
    then
        Comm.showMessage("Zespół dla Ciebie to Glenn Miller");
end

rule "Jamiroquai"
    when
        (or
            Fact(name("jazz"), value(true))
            Fact(name("rock"), value(true))
            Fact(name("acid jazz"), value(true))
        )
        Fact(name("guitar"), value(true))
        Fact(name("male vocal"), value(true))
        Fact(name("opera"), value(false))
        Fact(name("instrumental"), value(false))
        (or
            Fact(name("high tempo"), value(true))
            Fact(name("mid tempo"), value(true))
        )
        Fact(name("medium songs"), value(true))
        Fact(name("medium lyrics"), value(true))
    then
        Comm.showMessage("Zespół dla Ciebie to Jamiroquai");
end

rule "Andy McKee"
    when
        Fact(name("guitar"), value(true))
        Fact(name("acoustic guitar"), value(true))
        Fact(name("solo"), value(true))
        Fact(name("instrumental"), value(true))
        (or
            Fact(name("alt rock"), value(true))
            Fact(name("art rock"), value(true))
            Fact(name("folk"), value(true))
            Fact(name("acoustic rock"), value(true))
        )
        not Fact(name("known"), value(true))
    then
        Comm.showMessage("Wykonawca dla Ciebie to Andy McKee");
end

rule "RHCP"
    when
        Fact(name("rock"), value(true))
        Fact(name("guitar"), value(true))
        Fact(name("bass"), value(true))
        Fact(name("drums"), value(true))
        Fact(name("instrumental"), value(false))
        Fact(name("clean vocal"), value(true))
        Fact(name("male vocal"), value(true))
        Fact(name("opera"), value(false))
        Fact(name("solo"), value(false))
        (or
            Fact(name("alt rock"), value(true))
            Fact(name("art rock"), value(true))
            Fact(name("rapcore"), value(true))
        )
        not Fact(name("dzielnia"), value(true))
        Fact(name("medium songs"), value(true))
    then
        Comm.showMessage("Zespół dla Ciebie to Red Hot Chili Peppers");
end

rule "Yeasayer"
    when
        (or
            Fact(name("pop"), value(true))
            Fact(name("rock"), value(true))
            Fact(name("electro"), value(true))
        )
        Fact(name("guitar"), value(true))
        Fact(name("solo"), value(false))
        Fact(name("male vocal"), value(true))
        Fact(name("opera"), value(false))
        Fact(name("clean vocal"), value(true))
        Fact(name("instrumental"), value(false))
        (or
            Fact(name("house"), value(true))
            Fact(name("alt rock"), value(true))
            Fact(name("art rock"), value(true))
            Fact(name("soft rock"), value(true))
            Fact(name("indie pop"), value(true))
            Fact(name("dream pop"), value(true))
        )
        Fact(name("short songs"), value(true))
        Fact(name("dzielnia"), value(false))
        (or
            Fact(name("slow tempo"), value(true))
            Fact(name("mid tempo"), value(true))
        )
    then
        Comm.showMessage("Zespół dla Ciebie to Yeasayer");
end



rule "Deep Purple"
    when
        (or
            Fact(name("hard rock"), value(true))
            Fact(name("heavy metal"), value(true))
            Fact(name("acid rock"), value(true))
        )
        Fact(name("guitar"), value(true))
        Fact(name("known"), value(true))
        Fact(name("solo"), value(false))
        Fact(name("male vocal"), value(true))
        Fact(name("opera"), value(false))
        Fact(name("scream"), value(false))
        Fact(name("clean vocal"), value(true))
        Fact(name("instrumental"), value(false))
        Fact(name("medium songs"), value(true))
        (or
            Fact(name("mid tempo"), value(true))
            Fact(name("fast tempo"), value(true))
        )
    then
        Comm.showMessage("Zespół dla Ciebie to Deep Purple");
end

rule "Riverside"
    when
        (or
            Fact(name("progressive rock"), value(true))
            Fact(name("progressive metal"), value(true))
        )
        (or 
        	Fact(name("guitar"), value(true))
        	Fact(name("drums"), value(true))
        	Fact(name("bass"), value(true))
        	Fact(name("piano"), value(true))
        )
        Fact(name("solo"), value(false))
        Fact(name("male vocal"), value(true))
        Fact(name("opera"), value(false))
        Fact(name("scream"), value(false))
        Fact(name("clean vocal"), value(true))
        Fact(name("long songs"), value(true))
    then
        Comm.showMessage("Zespół dla Ciebie to Riverside");
end

rule "Peja"
    when
        Fact(name("hiphop"), value(true)) 
        (or 
        	Fact(name("dzielnia"), value(true))
        	Fact(name("blaster"), value(true))
        )
        Fact(name("solo"), value(true))
        Fact(name("male vocal"), value(true))
        Fact(name("opera"), value(false))
        Fact(name("scream"), value(false))
        Fact(name("medium songs"), value(true))
    then
        Comm.showMessage("Peja to Twój wybór, to Twoja rzeczywistość.");
end
