package rules

import com.sample.*;

rule "Ask instruments"
	when
		q : Question(isId(2))
	then
		Comm.askQuestion(q);
		q.asked();
end

rule "Ask guitars"
    when
    	Fact(name("guitar"), value(true))
        q : Question(isId(3))
    then
        Comm.askQuestion(q);
        q.asked();
end

rule "Ask syths"
    when
    	Fact(name("synth"), value(true))
        q : Question(isId(4))
    then
        Comm.askQuestion(q);
        q.asked();
end

rule "Ask genres"
	when
		q : Question(isId(9))
	then
		Comm.askQuestion(q);
		q.asked();
end

rule "Ask blues"
	when
		Fact(name("blues"), value(true))
		q : Question(isId(10))
	then
		Comm.askQuestion(q);
		q.asked();
end

rule "Ask country"
	when
		Fact(name("country"), value(true))
		q : Question(isId(11))
	then
		Comm.askQuestion(q);
		q.asked();
end

rule "Ask electro"
	when
		Fact(name("electro"), value(true))
		q : Question(isId(12))
	then
		Comm.askQuestion(q);
		q.asked();
end

rule "Ask rock"
	when
		Fact(name("rock"), value(true))
		q : Question(isId(13))
	then
		Comm.askQuestion(q);
        q.asked();
end

rule "Ask metal"
	when
		Fact(name("metal"), value(true))
		q : Question(isId(14))
	then
		Comm.askQuestion(q);
        q.asked();
end

rule "Ask folk"
	when
		Fact(name("folk"), value(true))
		q : Question(isId(15))
	then
		Comm.askQuestion(q);
        q.asked();
end

rule "Ask hiphop"
	when
		Fact(name("hiphop"), value(true))
		q : Question(isId(16))
	then
		Comm.askQuestion(q);
        q.asked();
end

rule "Ask jazz"
	when
		Fact(name("jazz"), value(true))
		q : Question(isId(17))
	then
		Comm.askQuestion(q);
        q.asked();
end

rule "Ask pop"
	when
		Fact(name("pop"), value(true))
		q : Question(isId(18))
	then
		Comm.askQuestion(q);
        q.asked();
end

rule "Ask instrumental"
    when
        q : Question(isId(5), asked == false)
    then
        Comm.askQuestion(q);
        q.asked();
        update(q);
end

rule "Ask male vocal"
    when
    	Fact(name("instrumental"), value(false))
        pq : Question(isId(5), asked == true)
        q : Question(isId(6), asked == false)
    then
        Comm.askQuestion(q);
        q.asked();
        update(q);
end

rule "Ask opera"
    when
    	Fact(name("instrumental"), value(false))
        pq : Question(isId(5), asked == true)
        q : Question(isId(7), asked == false)
    then
        Comm.askQuestion(q);
        q.asked();
        update(q);
end

rule "Ask scream"
    when
    	Fact(name("instrumental"), value(false))
        pq : Question(isId(5), asked == true)
        q : Question(isId(8), asked == false)
    then
        Comm.askQuestion(q);
        q.asked();
        update(q);
end
