package rules

import com.sample.*;

rule "Start"
  when
    f : Fact(name("start"), value(true))
  then
  		f.setValue(false);
  		update(f);
		int i = 0;
    	insert(new Question(i++, "Test. wybierz tylko jedno:", Question.SINGLE, new Option[] {new Option("jedno"),new Option("drugo"),new Option("trzecio"),new Option("czwarto")}, false));

    	insert(new Question(i++, "Może metal?", Question.BOOLEAN, new Option[] {new Option("metal", new Fact("metal", true))}, false));

    	insert(new Question(i++, "Wybierz lubiane instrumenty", Question.MULTIPLE, new Option[] {new Option("bass"),new Option("guitar"),new Option("drums"),new Option("piano"), new Option("synth")}, true)); // 2

    	insert(new Question(i++, "Wybierz lubiane gitary", Question.MULTIPLE, new Option[] {new Option("gitara akustyczna"),new Option("gitara elektryczna"),new Option("gitara klasyczna")}, false)); // 3

    	insert(new Question(i++, "Wybierz lubiane syntezatory", Question.MULTIPLE, new Option[] {new Option("moog"),new Option("syth pad"),new Option("saw lead"),new Option("wobwobwobwobwobwob")}, false)); // 4

    	insert(new Question(i++, "Czy ma to być muzyka instrumentalna?", Question.BOOLEAN, new Option[] {new Option("instrumental")}, false)); // 5

      insert(new Question(i++, "Wokal męski?", Question.BOOLEAN, new Option[] {new Option("male vocal")}, false)); // 6

      insert(new Question(i++, "Spiew operowy?", Question.BOOLEAN, new Option[] {new Option("opera")}, false)); // 7

      insert(new Question(i++, "Scream?", Question.BOOLEAN, new Option[] {new Option("scream")}, false)); // 8

      insert(new Question(i++, "Jakie gatunki lubisz?", Question.MULTIPLE, new Option[] {new Option("blues"),new Option("country"),new Option("electro"),new Option("rock"),new Option("metal"),new Option("film"),new Option("folk"),new Option("gaming"),new Option("hiphop"),new Option("jazz"),new Option("poetry"),new Option("pop"),new Option("reggae"),new Option("classical"),new Option("disco")}, false)); // 9

      insert(new Question(i++, "Jakie podgatunki bluesa?", Question.MULTIPLE, new Option[] {new Option("boogie-woogie"),new Option("country blues"),new Option("electric blues"),new Option("piano blues"),new Option("chicago blues"),new Option("r&b"),new Option("jazz blues")}, false)); // 10

      insert(new Question(i++, "Jakie podgatunki country?", Question.MULTIPLE, new Option[] {new Option("close harmony"),new Option("nashville"),new Option("rockabilly")}, false)); // 11

      insert(new Question(i++, "Jakie podgatunki electro?", Question.MULTIPLE, new Option[] {new Option("industrial"),new Option("techno"),new Option("house"),new Option("dupstep"),new Option("uk garage")}, false)); // 12

      insert(new Question(i++, "Jakie podgatunki rocka?", Question.MULTIPLE, new Option[] {new Option("alt rock"),new Option("art rock"),new Option("rapcore"),new Option("glam rock"),new Option("grunge"),new Option("hard rock"),new Option("progressive rock"),new Option("punk rock"),new Option("soft rock")}, false)); // 13

      insert(new Question(i++, "Jakie podgatunki metalu?", Question.MULTIPLE, new Option[] {new Option("alt metal"),new Option("death metal"),new Option("nu metal"),new Option("post-metal"),new Option("progressive metal"),new Option("sludge metal"),new Option("doom metal"),new Option("symphonic metal"),new Option("viking metal"),new Option("neo-classical metal"),new Option("folk metal")}, false)); // 14

      insert(new Question(i++, "Jakie podgatunki folku?", Question.MULTIPLE, new Option[] {new Option("irish"),new Option("polish"),new Option("indian"),new Option("balkanian")}, false)); // 15

      insert(new Question(i++, "Jakie podgatunki hiphopu?", Question.MULTIPLE, new Option[] {new Option("gangsta rap"),new Option("rap opera"),new Option("psycho hiphop"),new Option("rap")}, false)); // 16

      insert(new Question(i++, "Jakie podgatunki jazzu?", Question.MULTIPLE, new Option[] {new Option("smooth jazz"),new Option("swing"),new Option("acid jazz"),new Option("funk"),new Option("ska")}, false)); // 17

      insert(new Question(i++, "Jakie podgatunki popu?", Question.MULTIPLE, new Option[] {new Option("synth pop"),new Option("brit pop"),new Option("indie pop"),new Option("symphonic pop"),new Option("dream pop")}, false)); // 18

      insert(new Question(i++, "Jak ważny jest dla Ciebie tekst?", Question.MULTIPLE, new Option[] {new Option("good lyrics"),new Option("medium lyrics"),new Option("lyrics dont matter"), new Option("nie wiem, nie znam sie, nie orientuje sie, zarobiony jestem")}, false)); // 19

      insert(new Question(i++, "Jak długie powinny być utwory?", Question.MULTIPLE, new Option[] {new Option("long songs"),new Option("medium songs"),new Option("short songs")}, false)); // 20

      insert(new Question(i++, "Będziesz słuchał muzyki, żeby pokazać się 'na dzielni'?", Question.BOOLEAN, new Option[] {new Option("dzielnia")}, false)); // 21

      insert(new Question(i++, "Będziesz katować innych tą muzyką przy pomocy głóśników w Twojej komórce?", Question.BOOLEAN, new Option[] {new Option("blaster")}, true)); // 22

      insert(new Question(i++, "Czy zespół musi być znany?", Question.BOOLEAN, new Option[] {new Option("known")}, true)); // 23

      insert(new Question(i++, "Wolisz wykonawcę solo czy zespół?", Question.BOOLEAN, new Option[] {new Option("solo")}, true)); // 22

end
