package rules

import com.sample.*;

rule "Start"
  when
    f : Fact(name("start"), value(true))
  then
		int i = 0;
    	insert(new Question(i++, "Może metal?", "boolean", new Option[] {new Option("metal", new Fact("metal", true))}, true));

    	insert(new Question(i++, "Wybierz lubiane instrumenty", "multiple", new Option[] {new Option("bass"),new Option("guitar"),new Option("drums"),new Option("piano"), new Option("synth")}, true));

    	insert(new Question(i++, "Wybierz lubiane gitary", "boolean", new Option[] {new Option("gitara akustyczna"),new Option("gitara elektryczna"),new Option("gitara klasyczna")}, false));

    	insert(new Question(i++, "Wybierz lubiane syntezatory", "boolean", new Option[] {new Option("moog"),new Option("syth pad"),new Option("saw lead"),new Option("wobwobwobwobwobwob")}, false));

    	insert(new Question(i++, "Czy ma to być muzyka instrumentalna?", "boolean", new Option[] {new Option("instrumental")}, true));

      insert(new Question(i++, "Wokal męski czy żeński?", "boolean", new Option[] {new Option("male vocal")}, false));

      insert(new Question(i++, "Spiew operowy?", "boolean", new Option[] {new Option("opera")}, false));

      insert(new Question(i++, "Scream?", "boolean", new Option[] {new Option("scream")}, false));

      insert(new Question(i++, "Jakie gatunki lubisz?", "multiple", new Option[] {new Option("blues"),new Option("country"),new Option("electro"),new Option("rock"),new Option("metal"),new Option("film"),new Option("folk"),new Option("gaming"),new Option("hiphop"),new Option("jazz"),new Option("poetry"),new Option("pop"),new Option("reggae"),new Option("classical"),new Option("disco")}, true));

      insert(new Question(i++, "Jaikie podgatunki bluesa?", "multiple", new Option[] {new Option("boogie-woogie"),new Option("country blues"),new Option("electric blues"),new Option("piano blues"),new Option("chicago blues"),new Option("r&b"),new Option("jazz blues")}, false));

      insert(new Question(i++, "Jakie podgatunki country?", "multiple", new Option[] {new Option("close harmony"),new Option("nashville"),new Option("rockabilly")}, false));

      insert(new Question(i++, "Jakie podgatunki electro?", "multiple", new Option[] {new Option("industrial"),new Option("techno"),new Option("house"),new Option("house"),new Option("house"),new Option("house"),new Option("dupstep"),new Option("uk garage")}, false));
end

rule "test"
  when
    f : Fact(name("bas"))
  then
    Comm.showMessage("Bas!!");
end
